In [2]:
#how to use numpy array
import numpy as np
my_list = [1,2,3,4,5,6]
print(type(np.array(my_list)))
arr = np.array(my_list)
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [3]:
#use of numpy arange function
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#advance in arange function
print(np.arange(0,10,2))


[0 2 4 6 8]


In [5]:
#zeros matix example function
arr = np.zeros(5)
print(arr)
#it creates floating point zeros 

[0. 0. 0. 0. 0.]


In [7]:
arr = np.zeros((3,5)) #it creates 3*5 matix and it takes tuple as argument
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#for uniray matrix
arr = np.ones((3,5)) #it creates 3*5 matix and it takes tuple as argument
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#use of random value
print(np.random.randint(0,10))
print(np.random.randint(0,1000,(4,4)))#create random no  from 0-1000 of 4*4 matrix


7
[[353 889 939 170]
 [134 765 330 882]
 [444 714 319 269]
 [294 231 314 234]]


In [18]:
#use of random value of constant
np.random.seed(101)
print(np.random.randint(0,1000,10))#this same is not change 


[863 523 337 838 575 599  75 393 973 552]


In [20]:
#get max value
np.random.seed(101)
arr = np.random.randint(0,1000,10)
print(arr)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.argmax())
print(arr.argmin())
print(arr.reshape(2,5))#dimention must be exist


[863 523 337 838 575 599  75 393 973 552]
973
75
572.8
8
6
[[863 523 337 838 575]
 [599  75 393 973 552]]


In [27]:
#use short form
mat = np.arange(0,100).reshape(10,10)
print(mat)
print(mat[2,2])
mat[0,:]#only a rows
mat[:,0]#only a rows
mat[0:3,0:3]#split the array 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
22


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [2]:
# use basic ndarray functions
import numpy as np
arr = np.array([[1,2,3,4,5],[9,8,7,6,5]])

# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 5)
Size of array:  10
Array stores elements of type:  int32


In [3]:
import numpy as np
arr = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print(arr)

[[1. 2. 4.]
 [5. 8. 7.]]


In [5]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print(d)



[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [8]:
#indexing in numpy
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
 # boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [14]:
#numpy basic operation
a = np.array([1, 2, 5, 3])
 
# add 1 to every element
print ("Adding 1 to every element:", a+1)

# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
 # multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)#T is stand for tracspose

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
 
# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))

a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])

# add arrays
print ("Array sum:\n", a + b)
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
 
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
Largest element is: 8.0
Row-wise maximum elements: [4. 6. 8. 4.]
Column-wise minimum elements: [-1. -7.  0.  0.]
Sum of all array elements: 34.1
Cumulative sum along each row:
 [[-1.   1.   1.   5. ]
 [ 4.   3.5  9.5  9.5]
 [ 2.6  2.6  9.6 17.6]
 [ 3.  -4.   0.   2. ]]
Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [15]:
#Numpy Universal function
# Python program to demonstrate
# universal functions in numpy
import numpy as np
 
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
 
# square root of array values
print ("Square root of array elements:", np.sqrt(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]
