In [2]:
#how to use numpy array
import numpy as np
my_list = [1,2,3,4,5,6]
print(type(np.array(my_list)))
arr = np.array(my_list)
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [3]:
#use of numpy arange function
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#advance in arange function
print(np.arange(0,10,2))


[0 2 4 6 8]


In [5]:
#zeros matix example function
arr = np.zeros(5)
print(arr)
#it creates floating point zeros 

[0. 0. 0. 0. 0.]


In [7]:
arr = np.zeros((3,5)) #it creates 3*5 matix and it takes tuple as argument
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#for uniray matrix
arr = np.ones((3,5)) #it creates 3*5 matix and it takes tuple as argument
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#use of random value
print(np.random.randint(0,10))
print(np.random.randint(0,1000,(4,4)))#create random no  from 0-1000 of 4*4 matrix


7
[[353 889 939 170]
 [134 765 330 882]
 [444 714 319 269]
 [294 231 314 234]]


In [18]:
#use of random value of constant
np.random.seed(101)
print(np.random.randint(0,1000,10))#this same is not change 


[863 523 337 838 575 599  75 393 973 552]


In [20]:
#get max value
np.random.seed(101)
arr = np.random.randint(0,1000,10)
print(arr)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.argmax())
print(arr.argmin())
print(arr.reshape(2,5))#dimention must be exist


[863 523 337 838 575 599  75 393 973 552]
973
75
572.8
8
6
[[863 523 337 838 575]
 [599  75 393 973 552]]


In [27]:
#use short form
mat = np.arange(0,100).reshape(10,10)
print(mat)
print(mat[2,2])
mat[0,:]#only a rows
mat[:,0]#only a rows
mat[0:3,0:3]#split the array 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
22


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [2]:
# use basic ndarray functions
import numpy as np
arr = np.array([[1,2,3,4,5],[9,8,7,6,5]])

# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 5)
Size of array:  10
Array stores elements of type:  int32
